### ISSUE TITLE
uploading app

### ISSUE THREAD

**Issue by miskayapp** [inspireui/fluxbuilder#85] opened 2020-05-23 12:04 UTC
i keep getting this error, while i try to upload the app, "This bundle is invalid - The Info.plist file is missing or could not be parsed"

**Comment by miskayapp** [comment] 2020-05-23 12:07
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleDisplayName</key>
	<string>Miskay</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Miskay</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(MARKETING_VERSION)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>miskayboutique.com</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>Miskay</string>
				<string>fb430258564493822</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.googleusercontent.apps.117181301928-ctli4epssdmkshg0tg8oa9smlt5udnub</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>
	<key>FacebookAppID</key>
	<string>430258564493822</string>
	<key>FacebookDisplayName</key>
	<string>Miskay</string>
	<key>FirebaseAppDelegateProxyEnabled</key>
	<false/>
	<key>GADApplicationIdentifier</key>
	<string>ca-app-pub-7432665165146018~2664444130</string>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>itms</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSAllowsArbitraryLoadsInWebContent</key>
		<true/>
	</dict>
	<key>NSCameraUsageDescription</key>
	<string>This app requires access to take the photo from camera</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>Need current location access</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Get your current location for delivery</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>This app requires</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>This app requires access to the photo library to support Chat Features.</string>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>io.flutter.embedded_views_preview</key>
	<string>YES</string>
</dict>
</plist>

**Comment by miskayapp** [comment] 2020-05-23 12:07
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleDisplayName</key>
	<string>Miskay</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Miskay</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(MARKETING_VERSION)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>miskayboutique.com</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>Miskay</string>
				<string>fb430258564493822</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.googleusercontent.apps.117181301928-ctli4epssdmkshg0tg8oa9smlt5udnub</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>
	<key>FacebookAppID</key>
	<string>430258564493822</string>
	<key>FacebookDisplayName</key>
	<string>Miskay</string>
	<key>FirebaseAppDelegateProxyEnabled</key>
	<false/>
	<key>GADApplicationIdentifier</key>
	<string>ca-app-pub-7432665165146018~2664444130</string>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>itms</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSAllowsArbitraryLoadsInWebContent</key>
		<true/>
	</dict>
	<key>NSCameraUsageDescription</key>
	<string>This app requires access to take the photo from camera</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>Need current location access</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Get your current location for delivery</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>This app requires</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>This app requires access to the photo library to support Chat Features.</string>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>io.flutter.embedded_views_preview</key>
	<string>YES</string>
</dict>
</plist>
` thats my info.plist

**Comment by minhcasi** [comment] 2020-05-25 01:58
@miskayapp - the solution from #88 will fix this issue

Please help us to comment your all issue on this ticket, we will keep it open to support you :)

**Comment by miskayapp** [comment] 2020-05-25 17:23
`
#88 IS NOT FIXING, IM STILLL GETTING THE SAME ERROR


`

**Comment by miskayapp** [comment] 2020-05-26 06:20
the issue is not fixed,im still getting the same error, its been 3 whole
days now

**Comment by minhcasi** [comment] 2020-05-27 00:37
Duplicate of #92

**Closed by minhcasi** 2020-05-27 00:37 UTC
Labels: help wanted, iOS
