### ISSUE TITLE
“The cache image is not configured”

### ISSUE THREAD

**Issue by danielo83** [inspireui/fluxbuilder#144] opened 2020-07-01 01:20 UTC
Hi, I see this error... :(
Image thumbnail plugin is already installed and configured 
![4044FC45-4D2F-4ADF-94E1-5C53BF34C285](https://user-images.githubusercontent.com/4254783/86192371-be6c5980-bb49-11ea-9f62-1a7c2c762424.jpeg)

**Comment by danielo83** [comment] 2020-07-01 11:16
I forgot to specify that no image is visible in the app

**Comment by minhcasi** [comment] 2020-07-02 02:57
@vumanhsn97 - pls help to investigate the issue

**Comment by vumanhsn97** [comment] 2020-07-02 08:43
@danielo83 
Make sure you press Regenerate Thumbnails button in your wordpress site and waiting for loading successful
Thanks!

**Comment by Goldingarts** [comment] 2020-07-02 21:34
Hi, you pulled my issue stating that it's a duplicate of this one, it's not.
I use a plugin to pull in posts from my Facebook pages, no images are stored on the server but are all linked to Facebook storage to save space.

Can your program detect this?

Regenerate thumbnails is installed but does nothing.

**Comment by vumanhsn97** [comment] 2020-07-03 02:28
@Goldingarts 
The cache image is a warning. It is not error
Try with this step to fix blank image:
- go to your fluxnews project folder
- go to lib/models/blog_news.dart
- add this code: if (imageFeature == null && imgMedia != null && imgMedia[0]['source_url'] != null) {
          imageFeature = imgMedia[0]['source_url'];
        }
like image https://tppr.me/aaFl5

**Comment by danielo83** [comment] 2020-07-03 07:36
Thank you to all, now it works :)

Il giorno ven 3 lug 2020 alle ore 04:28 vumanhsn97 <notifications@github.com>
ha scritto:

**Closed** 2020-07-03 07:43 UTC
Labels: image-cache
