### ISSUE TITLE
GraphQL Errors

### ISSUE THREAD

**Issue by kangsotheara** [inspireui/fluxbuilder#70] opened 2020-05-10 07:51 UTC
On Checkout page - Section SHIPPING

There is an issue with the app during request the data, place contact admin for fixing issues Exception: GraphQL Errors.
Variable checkoutid of type ID! was provided invalid value Undefined location.

![photo_2020-05-10_14-49-54](https://user-images.githubusercontent.com/2009861/81493798-a4db2e00-92cd-11ea-87b5-b6ff13bbadc8.jpg)

**Comment by minhcasi** [comment] 2020-05-11 01:46
Duplicate of #3129

**Closed by minhcasi** 2020-05-11 01:46 UTC
