### ISSUE TITLE
Warning: FormatException: Unexpected character (at chaacter1)

### ISSUE THREAD

**Issue by opooletech** [inspireui/fluxbuilder#65] opened 2020-05-08 12:29 UTC
Warning: FormatException: Unexpected character (at chaacter1)
Dear sir having issue in signin signup please help to resolve the issue
even everything correct connect
Be sure you have pasted the SHA-1 key to your Firebase setting. Check more in https://docs.inspireui.com/fluxstore/common-issues/ - thank you
Everything done even purchase key enter also in mstore
but still having issue in signin or signup product show in app

**Comment by minhcasi** [comment] 2020-05-09 04:59
Duplicate of #3097

**Closed by minhcasi** 2020-05-09 04:59 UTC
