### ISSUE TITLE
fluxbuilder not work on window os inspireui/support

### ISSUE THREAD

**Issue by Cheewingtan** [inspireui/fluxbuilder#154] opened 2020-07-13 08:47 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

Hi ,could you update me this issue ?https://github.com/inspireui/fluxbuilder/issues/151#issuecomment-657353496
is already two days

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment] 2020-07-13 12:49
@Cheewingtan - could you share the screenshot error pls?

**Comment by Cheewingtan** [comment] 2020-07-15 03:28
> @Cheewingtan - could you share the screenshot error pls?
https://github.com/inspireui/fluxbuilder/issues/151
please go this link , 5 day ago...

**Comment by minhcasi** [comment] 2020-07-15 04:05
Duplicate of #151

**Closed by minhcasi** 2020-07-15 04:05 UTC
